version: '3'
services:

  frontend:
    image: mnsgarage-frontend:tag
    container_name: mnsgarage_frontend
    build:
      context: ./path/to/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
volumes:
  dbdata:
