name: Deploy React App

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  create-folder:
    name: Création du dossier
    runs-on: ubuntu-latest
    steps:
      - name: Créer le dossier sur la machine distante
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /opt/app/garage/front-garage

  build:
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build --if-present

  deploy:
    name: Déployer l'application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy build files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: build/.
          target: /var/www/mnsgarage/

